### ISSUE TITLE
¿How to start the daemon without the config file?

### ISSUE THREAD

**Issue by kkblownt** [forknote/forknote#100]
If i already set the all parameters manually in CryptoNoteConfig.h and the others files, ¿why specify it again with the config file? ¿Is possible start the daemon of any form without this config file?

**Comment by uncmart** [comment]
Yes, set default value and config file default path.

**Comment by pmitchev** [comment]
Why use forknote if you set your parameters in CryptoNoteConfig.h?

**Comment by kkblownt** [comment]
@pmitchev only for tests
