### ISSUE TITLE
Inconsistent use of paymentId parameter in Windows / Linux

### ISSUE THREAD

**Issue by indigencoin** [forknote/forknote#106]
I'm using walletd for Windows, and whenever I add `paymentId ` in my json parameters for `sendTransaction`, I get this error result:

{"error":{"code":-32600,"message":"Invalid Request"},"id":"","jsonrpc":"2.0"}

But when I use `payment_id`, the transaction gets through with no errors.

However, I noticed in my walletd running on Linux where the receiving wallet address is, the `getTransaction` method is expecting `paymentId` parameter (and NOT `payment_id`) so the payment id is always blank in all incoming transactions.

**Comment by indigencoin** [comment]
Never mind, I found the problem in the source code. paymentId is correct but it conflicts with another parameter. Problem solved.

**Comment by pmitchev** [comment]
What was the incorrect parameter?
