### ISSUE TITLE
Upgrading Zawy difficulty algorithm 

### ISSUE THREAD

**Issue by zawy12** [forknote/forknote#107]
Sorry for making this post so long.  Here's a short summary: Use [LWMA difficulty algorithm](https://github.com/zawy12/difficulty-algorithms/issues/3) instead of my older Zawy algorithms or the Cryptonote default.

I just found out (after probably forgetting) that forknote coins have been using one of my difficulty algorithms from last year.  I have not seen the code to see if it's correct, and I do not know exactly which algorithm has been used.  I saw N=17 mentioned, so coins must be using one of my really fast, older ones that Karbowanec and Sumokoin were the first to use.   N=17 does not work very well, and I think it will mess up any coins that have a faster solvetime than Karbowanec and Sumokoin which is T=240 seconds.  Even for Karbo and Sumo, it's not a very good algorithm.  It works and it does not always "break" like N=720 in the default Cryptonote/Monero algo, but the metrics on its performance are not near as good as other options.  My apologies for making N too small, and for not knowing to warn coins that T<240 is not likely to work well.   Karbo and Sumo have not forked to make it better and it's been 1.5 years for Karbo and 1 yr for Sumo.  The problem is that it varies up and down too much on accident which constantly attracts miners when it goes low.  On the plus side, it also rises up very quickly when big miners do jump on, so they do not stay on it long.  It also falls fast after an attack, so it does not typically get stuck with catastrophic delays like Cryptonote/Monero clones experience.

If you're having a problem with an old Zawy algorithm, and if the implementation is good, then the N value is probably the problem.  The N you should select for a simple moving average for a small to medium size coin is ```N=int(40*(600/T)^0.3))```.  [Here](https://github.com/zawy12/difficulty-algorithms/issues/9) is my newest design for SMA algos.  [Here](https://github.com/zawy12/difficulty-algorithms/issues/14) is my discussion for why this formula for N is the best I can come up with for small to medium-size coins.

If the N value is not the problem, and the implementation is good, then maybe miners are manipulating it with bad timestamps.  I know tricks for that and how to stop them, but I have not seen a case on a live coin where miners are actually doing it.

But there are three options better than SMA. The first is my improvement of Digishield V3 which is also shown in my first link above for the SMA.  The 2nd is an [EMA](https://github.com/zawy12/difficulty-algorithms/issues/21).  But the best one is [LWMA](https://github.com/zawy12/difficulty-algorithms/issues/3) and Monero/Cryptonote clones seem to be on the verge of a stampede for it.  Four of them switched to it from Monero/Cryptonote's default in the past 2 months.  Bitcoin gold is about to implement it.  [Here](https://github.com/zawy12/difficulty-algorithms/issues/23) is a review of how much the Monero clones improved after implementing it.

Again, my apologies for messing coins up with an N that's too small. Masari was the first one I heard from who had a problem with N=17 and they were the first to use LWMA with great success.  They and another coin credit LWMA for big price increases because it fixed delays. 

If you have had problems with my algorithm or if you want me to review how your difficulty is performing, please [email me](zawy@yahoo.com) up to 60,000 blocks of data with block number, timestamp (as seconds since 1970 which is a long number beginning with 15.....) and the difficulty for that block.  You can also send me a link to the core of the difficulty code (since github is not hardly searchable for forks) that calculates the difficulty, but I'm more likely to review code if you write it out in pseudocode for me like I've done in all the links above.

**Comment by 2acoin** [comment]
@zawy12 If I am creating a coin with a block time of 90 seconds using ForkNote. Then, what ZAWY N=? what you suggest?

I tried running with Zawy N=17 and it ran for about 200 blocks and then it just hung. Disabling ZAWY using N={noting} let me restart and it's been running fine but it looks like it is not doing a good job of calculating the difficulty per block.

**Comment by zawy12** [comment]
The pseudocode says to use 90.  Read the pseudo code on the page again and see the recommended commits. We're working on a pull for forknote

**Comment by pmitchev** [comment]
This is not how ZAWY_DIFFICULTY_BLOCK_INDEX works. ZAWY_DIFFICULTY_BLOCK_INDEX is block height. It's better this way than introducing new major block version for every hardforking change

**Comment by zawy12** [comment]
Where is your code? I'll review it to see if I can find a problem. The lwma page says to look at karbo, haven, or dosh code. Again, please read the lwma page again. That formula is a week or two old. There have been changes. The is the most recent commit:

https://github.com/dosh-project/dosh/pull/2#commits-pushed-b85d646

**Comment by 2acoin** [comment]
@pmitchev The default for forknote ZAWY_DIFFICULTY_BLOCK_INDEX=30 causes a coin with 90 second block time to hang after about 200 blocks.

I am trying to determine the proper setting for this value based on a 90 second block time.

Any suggestions?

@zawy12 has stated that the code for forknote is using old difficulty calculations and should be updated. I am just trying to get a stable group of settings so that I can launch our coin.

**Comment by zawy12** [comment]
Where do you see ```N=int(40*(600/90)^0.3) = 70``` at forknote?  As far as I know forknote only has the old simple moving average with N=17 (aka zawy v1)

There are no settings that should cause it to hang.  What code are you using?

**Comment by zawy12** [comment]
@2acoin are you in our difficulty discord?  email me at zawy@yahoo.com if you need an invite.

**Comment by 2acoin** [comment]
@zawy12 Maybe it's my misunderstanding of the settings.

By default I see the following in the coin.config file for forknote;
**DIFFICULTY_WINDOW=17
ZAWY_DIFFICULTY_BLOCK_INDEX=30**

If I run with these default settings my daemon/pool run fine for about 200 blocks where at which point I get the following error;
**ERROR difficulty overhead
ERROR failed to create block temple**

If I comment out the ZAWY setting then it runs fine but the difficulty never goes above 1.

I'm looking for an answer as to what setting I should be using and if I should implement the LWMA Difficulty code.

**Comment by zawy12** [comment]
I'm closing this in order to start a clean thread.

**Comment by 2acoin** [comment]
@pmitchev my issue occurs even when a miner is mining on the pool.

**Comment by SoraKohaku** [comment]
https://github.com/FndNur1Labs/catav3/issues/14

for info we need fixed constant zawy or lwma

**Comment by mewmix** [comment]
Same issue for me but i shut my miner off for 6 hours :(
