### ISSUE TITLE
LWMA difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [forknote/forknote#112]
Here's my current version of "the best" difficulty algorithm. 

[Wownero has this with all the relevant commits](https://github.com/wownero/wownero/pull/1/commits/efe03eb0379d87d521f6fc86cef39ec06c119f41)

The one here at forknote is a copy of karbowanec's that may be a little dated, not having complete instructions and such.

See the most recent version at  https://github.com/zawy12/difficulty-algorithms/issues/3

I delete code from this post in order to keep master copy in one place..

**Comment by zawy12** [comment]
I have not heard back from haendev, kaikzero, or wowario.    so now I guess it's up to @pmitchev or @aivve

**Comment by zawy12** [comment]
I'm getting emails from people looking for code.  If your a cryptonote/forknote/monoero/bytecoin clone,   see [Haven](https://github.com/havenprotocol/haven/issues/3#issuecomment-378203016) and [Wownero](https://github.com/jwinterm/wownero/pull/3).   The only important difference of these from the above is to set future time limit to 500 instead of 7xT.

**Comment by pmitchev** [comment]
I am working on adding Karbo's implementation. I will probably have the code today

**Comment by zawy12** [comment]
Karbo should be the exact same, but they may not have the comments update as well as the other two, but mainly karbo was making a lot of other changes so it might be harder to follow the commits.  That's why I send people to the other coins.  But it sounds like karbo has some good new protection against txn DOS that you might need, if he's the same type of coin as forknote.

**Comment by aivve** [comment]
Actually it could be implemented better. Instead of adding + 1 in `const size_t   DIFFICULTY_WINDOW_V3                          = 60 + 1;` it is better to add that + 1 to get extra difficulty and timestamp for the vectors in Blockchain.cpp so that DIFFICULTY_WINDOW_V3 = N.

**Comment by zawy12** [comment]
I have another change.   Change BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW to 11 instead of 60.  I believe this is used to get the oldest timestamp that a block can assign via the median of 11.  So typically a block can't have a timestamp that is older than the 6th block in the past.  BTC uses this "MTP" of 11.   This change combined with future_time_limit set to 500 seconds means that we can remove the +7 / -7 limits in the code, or rather, comment them out and write a comment to explain when to include it.

**Comment by zawy12** [comment]
Aivve has concerns about the changing the MTP, so I'll retract that change.  It's too new and I don't know the consequences, so I can't recommend it for forknote.  I'm retracting previous comment.

**Comment by aivve** [comment]
It looks like in Forknote it's used only in [validateBlock](https://github.com/forknote/forknote/blob/master/src/CryptoNoteCore/Core.cpp#L1435-L1441) function so it possibly can be changed safely. In ~~older~~ other versions  (Bytecoin v. 1.0~) it's used also elsewhere, for example in `handle_alternative_block` function so I'd cautious.

**Comment by zawy12** [comment]
I have a way to prevent a chain from ever locking up. The possibility is kind of remote for LWMA, especially if the coin is not really, but it's a still a possibility with LWMA.

But there is a code change I don't know how to do:  this "solvetime" below is the submitted timestamp minus the most recent timestamp.  I need "submitted" timestamp available in the difficulty algorithm.

Add the following just before next_D is returned:
```
If (solvetime > (7+2*6)*T + FTL) {
   next_D = next_D * T * 5 / (solvetime - 7*T - FTL) / 
} 
```


This is how it works:  If a timestamp is ```(7+2x5)xT+FTL``` after previous timestamp, next_D is 1/2 of what it was supposed to be.  At ```(7+3x5)xT+FTL```, it is 1/3, at ```(7+4x5)xT + FTL``` it is 1/4,  and so on.   The 5 comes from this:  if a big miner drives it up 300%, then it will be very uncommon (0.9% of the time the block that immediately follow the attack can do this on accident, so this can be activated only with ideal manipulation in 1% of attacks) for the network to take 3.00x5xT seconds to find a block for it.   So this code will rarely get activated on accident when it is combined when maximum manipulation (7+FTL).  Maximum manipulation is this:  big miner drives difficulty up 300%.  He sends -7xT timestamp which is the max.  He waits and hopes honest miners are very unlucky and it has been 5x3xT seconds and no one has found a block. So now he can send a timestamp that is (7+5x3)xT + FTL after the previous block to activate this code.  And that makes difficulty drop to 1/3.  But notice, that is exactly what difficulty is supposed to be, because he waited, and because he was waiting (not mining), hashrate needed to be 1/3.  But then he can begin an attack again thanks to this. But he can do this only 1% of the time.  

Example: If a 100x attacker is really trying to lock your chain, he will run 100x hashpower for N blocks to drive it up 100x and go away.  So all of your miners should be motivated to leave which permanently locks your chain. But after (5x100+7)xT +FTL, blocks (about 500) all miners aware of this code should be motivated to come back.  After 1000 blocks, difficulty will be at 1/2 price, so it's a really strong motivation.

**Comment by zawy12** [comment]
To be clear, my previous comment is not for what forknote will implement because it's a major change to use that extra variable in difficulty, and to make sure pools know when they can submit a lower difficulty than the previous block indicates.

For safety reasons to protect against chain splits, I've changed FTL = 500 (which was 7xT ) to be 3xT as long as > 500 seconds.

**Comment by zawy12** [comment]
I deleted the line ```
assert(n <= DIFFICULTY_WINDOW_V2);``` because it should always be false after startup period ends. I do not know why wownero was able to execute because this should have always terminated.  I hope this fixes a problem wownero is having with this code:  somehow it is forcing N to be N-1.  Karbo's N=60 because in karbo:
```assert(n <= DIFFICULTY_WINDOW_V2);```
is the same as:
```assert(n <= N+1);``` 
But my previous code above it meant:
```assert(n <= N);```
which is never true after first 60 blocks.

**Comment by aivve** [comment]
It would work if in function would be passed ready to use difficulties and solve times. But in function are passed cumulative difficulties and timestamps. To get individual difficulties and solve times we have to substract from the current value the previous one in the loop, that's why we need to pass N + 1 timestamp and cumulative difficulty in the vectors. Refer to [these changes](https://github.com/seredat/karbowanec/commit/2f8c7e81f33f49ea1476e4fcf3c2dd611c93654b) if you want to have more clean algo implementation where N is the same as DIFFICULTY_WINDOW_V3, where I moved adding one additional element to vectors in other place.

**Comment by zawy12** [comment]
Where the changes you made in Blockchain.cpp necessary to remove the -1 in 

```N = DIFFICULTY_WINDOW_V3 - 1```?

**Comment by aivve** [comment]
In Karbo this file is quite different. This additional element is passed [here](https://github.com/seredat/karbowanec/commit/2f8c7e81f33f49ea1476e4fcf3c2dd611c93654b#diff-eb8416efd4da61774083345a51ef2af7R67) in [this function](https://github.com/seredat/karbowanec/commit/2f8c7e81f33f49ea1476e4fcf3c2dd611c93654b#diff-6ad7f7ddc5e8e1d62ee9fb57e0b1ff83R697)  (depending of the version of the block and algo).

**Comment by zawy12** [comment]
I don't understand. I get exactly your results in my spreadsheet.  But Haven and Wownero are not getting the exact same thing as me, but their code in Difficulty.cpp looks mathematically exactly the same as yours.

**Comment by zawy12** [comment]
What is timestamps.size before LWMA function?

**Comment by aivve** [comment]
I am passing N + 1 timestamps and cumulative difficulties, i.e. 61 to get 60 solvetimes and difficulties

**Comment by zawy12** [comment]
Is there any reason we can't replace all of the following

```
if (timestamps.size() > N) {
	timestamps.resize(N + 1);
	cumulative_difficulties.resize(N + 1);
}
size_t n = timestamps.size();
assert(n == cumulative_difficulties.size());
// If new coin, just "give away" first 5 blocks at low difficulty
if ( n <= 5 ) { return  1; }
// If height "n" is from 6 to N, then reset N to n-1.
else if (n < N+1) { N=n-1; }
```
With this?
```
// return a difficulty of 1 for first 3 blocks if it's the start of the chain
if (timestamps.size() < 4) { 
   return 1; 
}
// otherwise, use a smaller N if the start of the chain is less than N+1
else if ( timestamps.size() < N+1 ) { 
    N = timestamps.size() - 1; 
}
```
Why reduce timestamps and cumulativeDifficulties sizes if they are big enough.

**Comment by zawy12** [comment]
Where are your timestamps and cumulative difficulties vectors created?

**Comment by zawy12** [comment]
I think the problem in Haven and Wownero is:

```#define DIFFICULTY_BLOCKS_COUNT_V2                         DIFFICULTY_WINDOW_V2```
Should have been:  
```#define DIFFICULTY_BLOCKS_COUNT_V2                         DIFFICULTY_WINDOW_V2 + 1```

because outside of the LWMA algorithm, it was resizing the timestamps and cumulative_difficulties to be N instead of N-1  The variable is named incorrectly because in all difficulty algorithms, the vectors should be N+1, not "difficulty blocks count"   So really, it needs to be renamed, or the +1 inserted in Blockchain.cpp where DIFFICULTY_BLOCKS_COUNT is used to resize the vectors.

It was only by accident we had 
```else if (n < N+1) { N=n-1; }```
 which forced N=N-1 always which prevented the loop from attempting 
```
solveTime = timestamps[0] - timestamps[-1];
difficulty = cumulative_difficulties[0] -  cumulative_difficulties[-1]
```

**Comment by aivve** [comment]
Reducing timestamps in fact is not necessary, it is necessary for difficulties in case of arithmetic mean  `cumulative_difficulties.start() -  cumulative_difficulties.end()`. It was left from previous CN algo. Indeed if we pass needed number of elements into this function all this part can be replaced by your version.

**Comment by zawy12** [comment]
But we don't need to pass do we?  We can just keep ```N = DIFFICULTY_WINDOW_V2;```

**Comment by aivve** [comment]
Yes, your proposal is absolutely right. It's more clean and simple.

**Comment by aivve** [comment]
I'd probably left ```if (timestamps.size() > N + 1) {
			timestamps.resize(N + 1);
			cumulativeDifficulties.resize(N + 1);
		}``` just in case to be sure we get correct elements in loop.

**Comment by zawy12** [comment]
Oh, right.  I was wrongly thinking too many would not hurt.

**Comment by zawy12** [comment]
I just added to the end:
```else {  timestamps.resize(N+1) }```

**Comment by zawy12** [comment]
I made the change the top post above and added a comment:
 ```#define DIFFICULTY_BLOCKS_COUNT_V2 DIFFICULTY_WINDOW_V2 + 1```

If you don't hear back from me, wownero is working fine.

**Comment by zawy12** [comment]
Rather
```
else {  
   timestamps.resize(N+1);  
   cumulative_difficulties.resize((N+1);  
}
```

**Comment by vitorgamer58** [comment]
We are all eager to make the Fork in the Blood Donation Coin, just waiting for more information and instructions. 
N of BBRC is 720 Blocks I already intend to move to 60 on the fork.

as the forknote site generated the configuration file in this way, we are in blockchain V3, we will move to V4 on the Fork, requiring an update on the cryptonote-util version to be compatible.

**Comment by zawy12** [comment]
@vitorgamer58 Post a link to your commit here when it's done so I can review the code.

**Comment by vitorgamer58** [comment]
Okay, I'm using the Forknote code, I think with this configuration file it's going to work, could you tell me if it's correct?

Line 20 the DIFFICULTY_WINDOW_V3 is the difficulty for the V4 blocks and line 31 the UPGRADE_HEIGHT_V4=-1 to be in a future block when the Hash percentage in the new daemon reaches 90%

https://github.com/BloodDonationCoinDev/bbrc-config/blob/master/BloodDonationCoin.conf

**Comment by zawy12** [comment]
Please replace forknote's core LWMA algorithm Currency.cpp with this one:

https://github.com/zawy12/difficulty-algorithms/issues/3#issuecomment-375600752
