### ISSUE TITLE
Error in JSON sendTransaction method with RPC Wallet API

### ISSUE THREAD

**Issue by MyGaCoDev** [forknote/forknote#120]
Ok... Some help with me please...
This is the JSON used with command "sendTransaction", where:
GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i is the address wallet with balance in the container
and GXCFrxvo1FKCS15Ei2WicN5iyK1BmZ3PZMHrFEFzqy8Gd4itTq7t1tP1iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHJX5fkJ is the destination.... but there are an error and I don't see it.

I tried the following things:
- change format in fee and amount (with point and without point)
- The examples in website does not specific about what address must to set in changeAddress, so I set the wallet with origin balance.
- Avoid paymentId, and setting some custom code... no one works.

The JSON in post:
`{ "params":{ "anonymity":6, "fee":0.01000000, "unlockTime":0, "paymentId":"", "addresses":[ "GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i" ], "transfers":[ { "amount":123.00000000, "address":"GXCFrxvo1FKCS15Ei2WicN5iyK1BmZ3PZMHrFEFzqy8Gd4itTq7t1tP1iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHJX5fkJ" } ], "changeAddress":"GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i" }, "jsonrpc":"2.0", "id":"23", "method":"sendTransaction" }`

I got the following error:
`{"error":{"code":-32600,"message":"Invalid Request"},"id":"23","jsonrpc":"2.0"}`

Any idea?

**Comment by indigencoin** [comment]
Remove totally the "paymentId" parameter. It may or may not be included in the params, but if it is included, it can't be blank.

**Comment by MyGaCoDev** [comment]
Ok... I implemented your suggested... And I will keep this in mind when this be fixed. But the error is the same:
{"error":{"code":-32600,"message":"Invalid Request"},"id":"23","jsonrpc":"2.0"}

Still searching... :(

**Comment by dedrisproject** [comment]
Same problem

**Comment by xoenll** [comment]
encountered the same problem. Anybody with a fix?

**Comment by xoenll** [comment]
@MyGaCoDev did you manage to fix this?

**Comment by MyGaCoDev** [comment]
I'm still working on it... :(
Other way to solve this is changing the source code, but that will need a new compilation out of the box of the forknote core. That is a way that i don't want to walk... not yet.

**Comment by xoenll** [comment]
Seems to be like a big wall to our wallet release. Thanks for the response @MyGaCoDev !

**Comment by xoenll** [comment]
@MyGaCoDev I managed to completely send the transaction by removing the whole payment id from the request. Just have to let you know. cheers!

**Comment by MyGaCoDev** [comment]
@jaikun12 Do you mean the "paymentId" or the "id" parameter? I'm going to try this... Thanks

**Comment by xoenll** [comment]
@MyGaCoDev remove the "paymentId" parameter. This allowed me to send a transaction successfully.

**Comment by MyGaCoDev** [comment]
@jaikun12 In what language (developing your code) are you working your project?

**Comment by xoenll** [comment]
@MyGaCoDev currently using PHP to build the app and curl to send the requests.

**Comment by MyGaCoDev** [comment]
I'm working on C#, for the Windows wallet, but it was impossible for this issue. So my new way is to build the Android and IOs APP, and use all the wallet functions in the central seed in a Linux server. So in this case is possible to manage all the functionalities as @jaikun12 says... into the PHP language...
Thanks for everyone... I will be in touch in the release of the apps for MYGACO.
