### ISSUE TITLE
daemon got stuck after some usage period

### ISSUE THREAD

**Issue by pmitchev** [forknote/forknote#14]
error during write: TcpConnection::write, events & (EPOLLERR | EPOLLHUP) != 0

**Comment by RocksteadyTC** [comment]
I have just received this as well.` error during write: TcpConnection::write, events & (EPOLLERR | EPOLLHUP) != 0`

**Comment by pmitchev** [comment]
This might be related:
https://github.com/amjuarez/bytecoin/pull/83

**Comment by pmitchev** [comment]
Fixed in 2.1.2
