### ISSUE TITLE
solo mining 

### ISSUE THREAD

**Issue by ghost** [forknote/forknote#21]
How to start solo mining forknote with external miner for example `xmrig`, I cant't find any tutorial is it possible?

**Comment by typoworx-de** [comment]
I'm also interested in this still looking on how setup of forknoted/walletd and/or simplewallet has to be done for this.

**Comment by pmitchev** [comment]
Use **miner** or solo miners for Monero. Monero miners should work the same way. You should only change the daemon rpc port
