### ISSUE TITLE
walletd does not start

### ISSUE THREAD

**Issue by georgyous** [forknote/forknote#22]
There seem to be a problem with starting walled. This issue does not seem to be present in the bytecoin code.

./walletd  --container-file test
Fatal error: boost::bad_any_cast: failed conversion using boost::any_cast

./walletd --config quazarcoin.conf --container-file test
Configuration error: container-file parameter are required

I think it is related to how the --config parameter is implemented but my C skills are really limited.

if I add "container-file=test" to the config file it is back to:
./walletd --config quazarcoin.conf -g
Fatal error: boost::bad_any_cast: failed conversion using boost::any_cast

Redhat 7
Boost 1.58

Thanks

**Comment by pmitchev** [comment]
Hi mate,
-c option is mandatory. Use it with the path to your config file

**Comment by georgyous** [comment]
Hello,

It works, sorry for being an idiot in the first place....

Thanks
