### ISSUE TITLE
How to get the Genesis block reward first?

### ISSUE THREAD

**Issue by loctai** [forknote/forknote#25]
Hi.
How to get the Genesis block reward first?

**Comment by Royaltropico** [comment]
Hello
If you do not modify the parameters you can use the generated code when you click on "View config". Otherwise you copy the file obtained in your folder "configs", you delete the code generated in: 

GENESIS_COINBASE_TX_HEX =

Then you open the terminal in the folder forknote and you type:

./forknoted --config-file configs/yourblockchain.conf --print-genesis-tx

All that remains is to copy the code in the configuration file and "normally it's good"

**Comment by cycleworm** [comment]
Hi, 
i think the last post did not answer the question right?

I found an old document. I am not sure if this is still a vaild or the lastest way how to do it. 
I setup a config and tried it. It worked for me to generate premined coins. See screenshot.

![image](https://user-images.githubusercontent.com/493769/32147580-125daeec-bcea-11e7-8b26-3ab35bc09433.png)

One thing that i changed in the description below is the config PREMINED_PERCENT
to "**GENESIS_BLOCK_REWARD=2000000000000000000**"

though i got an error. **Maybe @pmitchev can give some insights how the actual way is to
generate a currency with premined coins? thanks**

![image](https://user-images.githubusercontent.com/493769/32147556-c820dbc4-bce9-11e7-8cc5-d515f085eaf6.png)

-------------------------------------------------------
_Example on Linux/Mac:

$ cat >testcoin.conf 

EMISSION_SPEED_FACTOR=18
DIFFICULTY_TARGET=120
CRYPTONOTE_DISPLAY_DECIMAL_POINT=12
MONEY_SUPPLY=18446744073709551615
**PREMINED_PERCENT=0**
DEFAULT_DUST_THRESHOLD=1000000
MINIMUM_FEE=1000000
CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=10
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE=60000
CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=86
p2p-bind-port=13539
rpc-bind-port=13540
BYTECOIN_NETWORK=e3df4e17-934c-9768-d63d-37df3503e80b
CRYPTONOTE_NAME=testcoin
UPGRADE_HEIGHT=1
If you want to learn more you can checkout the supported parameters of the configuration file.

Creating simplewallet addresses

This step is only required if your coin has premine

$ ./simplewallet --config-file configs/testcoin.conf --generate-new-wallet MY.wallet --password PASSWORD

config path exist
forknote wallet v1.0.8.1.614()
Sync from timestamp: 1444336575
Error: wallet failed to connect to daemon (http://localhost:13540).
Generated new wallet: FXhKiPxMdJ6LL1iqkEDWbk1BiiQ7SzHY1b3L9KqqPmP95e9toTXKvQSVGePtjfoDUhMPqSEKFhzymA84o6fGPhQiUYP92rT
view key: 18367126f3948849c1754d14e53702c046751ed7a108290f16bbfd5b3a71180e

Caution: Don’t forget to backup the wallets

Genesis coinbase transaction creation

For coins without premine

$ ./forknoted --config-file configs/testcoin.conf --print-genesis-tx

config path exist
Modify this line into your coin configuration file as is: 
GENESIS_COINBASE_TX_HEX=010a01ff0001ffffffffffff0f029b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f5142ee494ffbbd0880712101fc680aba69fb5028ade093fb1186ca9de4e65a369ca13ae75fdeef9e952b9449

For coins with premine

$ ./forknoted --config-file configs/testcoin.conf --print-genesis-tx \
 --genesis-block-reward-address FXhKiPxMdJ6LL1iqkEDWbk1BiiQ7SzHY1b3L9KqqPmP95e9toTXKvQSVGePtjfoDUhMPqSEKFhzymA84o6fGPhQiUYP92rT \
 --genesis-block-reward-address FPMfUYtRHcZJdL2nLDH7zi2bZUMzgdMPm8kHibeV4qLh8pfsvZsBF6eiHH8T2QkdZm4viA2F9S4YvUk2PXodvxRPDYVvXyR

config path exist
outs: 922337203685477580
outs: 922337203685477580
Modify this line into your coin configuration file as is: 
GENESIS_COINBASE_TX_HEX=010a01ff0002cc99b3e6cc99b3e60c024fe47e814d9f44c83184334fb3b5f9a4ab3ebb347050e3742729703086a5e130cc99b3e6cc99b3e60c021011cd9c37a669ea1e5a930cac793aa98431dfe77a9274385b4ed29e3e5e2ac021011afb48c42cbd0a72fc9d782580d6474cf68b5eaac224315447e9694809410930_
-------------------------------------------------------

**Comment by lanaiscool** [comment]
i as well did not get the block reward first and it will not find anymore blocks then 3  i got 3 transactions all 3 were 66 coins

**Comment by NEO2756** [comment]
@cycleworm 
Followed same steps. But no transaction with "Height 0" having premine coins as amount of coins.
My logs starts with "Height 1" and so on...
Two doubts:
1.  which transactions are getting mined as my wallet has balance with blcokchain height 5.
2. where are premine coins?
Any help appreciated.:)
