### ISSUE TITLE
Youtube tutorials

### ISSUE THREAD

**Issue by BitWill** [forknote/forknote#34]
Would be helpful if anybody had a YouTube tutorial on creating a coin with Forknote.

**Comment by ThePixelBro22** [comment]
Haha I would do it, once i actually get this to work.

**Comment by theheartofraven** [comment]
@ThePixelBro22 And how to compile a GUI wallet for this. Thanks! :)

**Comment by zhmrab** [comment]
Agreed, would love to have more info on how to get GUI

**Comment by prashantprabhakar** [comment]
Hope someone gets some time to help newbies to forkNote.

**Comment by lninjo123** [comment]
https://www.youtube.com/watch?v=Jtgbn3h3P9M
