### ISSUE TITLE
help i cant connect to seed nodes

### ISSUE THREAD

**Issue by kensukekita** [forknote/forknote#35]
`2017-Oct-07 16:52:54.206397 WARNING [127.0.0.1:60383 INC] Exception in connectionHandler: TcpConnection::read, WSAGetOverlappedResult failed, result=10054, Se ha forzado la interrupci¾n de una conexi¾n existente por el host remoto.`
i get a loop of that output with differents port numbers
what should i do? i'm working with my firewall turned off
also i'm working on 2 computers

now i'm getting this
2017-Oct-07 17:08:16.218887 INFO [127.0.0.1:61222 INC] WRONG NETWORK AGENT CONNECTED! id=339bb590-90e5-1161-b0da-5de2dd128754

what should i do?

**Comment by kensukekita** [comment]
now i'm getting this 
`2017-Oct-07 17:08:16.218887 INFO    [127.0.0.1:61222 INC] WRONG NETWORK AGENT CONNECTED! id=339bb590-90e5-1161-b0da-5de2dd128754`

**Comment by kensukekita** [comment]
what should i do?

**Comment by Jaydeep75** [comment]
CryptoNoteConfig.h

const std::initializer_list<const char*> SEED_NODES = {
  "127.0.0.1:29090"
 };
server ip with p2p port

**Comment by indigencoin** [comment]
hi, you should add the port numbers (p2p and rpc) on your firewall settings to allow connections both INCOMING and OUTGOING. I had the same issue when I added them on the Incoming list only. Adding them on the Outgoing list solved it.

**Comment by kensukekita** [comment]
both answers solved my issues :)
