### ISSUE TITLE
simplewallet hangs up on Windows 10

### ISSUE THREAD

**Issue by indigencoin** [forknote/forknote#36]
Hi, I have successfully ran 2 seed nodes and both seems connected. Then I ran forknoted on my desktop running Windows 10, and after it synchronized it says I can now run simplewallet, However, when I ran simplewallet and successfully opened the wallet address, it hangs up and not accepting commands, even though the cursor is blinking. No error on the log file as well.

2017-Oct-15 21:25:00.430171 INFO    [simplewallet] forknote wallet v2.1.1.1245 ()
2017-Oct-15 21:25:00.434171 INFO    [simplewallet] Loading wallet...
2017-Oct-15 21:25:00.531238 INFO    [simplewallet] Opened wallet: iUzdZaigoapgGkxT4fwqvP8iBHeGAdCg4LyAr6GZjqhdVGvYknJjeacZnyJXP78tJVHvYKATawtgCEN35nYNvP2J2YFmpCA8F
2017-Oct-15 21:25:00.535239 INFO    [simplewallet] **********************************************************************
Use "help" command to see the list of available commands.
**********************************************************************

**Comment by indigencoin** [comment]
OK. I made it work. I had to run miner.exe first and pre-mine the genesis the block rewards before I must run simplewallet.

**Comment by sakshamapp** [comment]
please tell me how to run miner.exe what command you run

**Comment by pmitchev** [comment]
./miner --help
