### ISSUE TITLE
Failed to validate block 

### ISSUE THREAD

**Issue by madradio** [forknote/forknote#39]
I modified the CryptonoteConfig.h to the values copied from conf file. 

And when I run the QT wallet, It syncs the first blocks and I get this error for the 3rd block

> Failed to validate block bbccaaa63ea82ba4d40f6951b61db3287a324b1663c2e1857309c7xxxxxxxxxx: Wrong block version

I think this could be due to the config file but i'm not sure what need to be changed. Thanks

**Comment by pmitchev** [comment]
What qt wallet are you running?

**Comment by madradio** [comment]
I'm using this 

https://github.com/amjuarez/bytecoin-gui

**Comment by madradio** [comment]
This is the CryptoNoteConfig.h file that I'm using

> #pragma once
> 
> #include <cstddef>
> #include <cstdint>
> #include <limits>
> 
> namespace CryptoNote {
> namespace parameters {
> 
> const uint32_t CRYPTONOTE_MAX_BLOCK_NUMBER                   = 500000000;
> const size_t   CRYPTONOTE_MAX_BLOCK_BLOB_SIZE                = 500000000;
> const size_t   CRYPTONOTE_MAX_TX_SIZE                        = 1000000000;
> const uint64_t CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX       = 12;
> const uint32_t CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW          = 10;
> const uint64_t CRYPTONOTE_BLOCK_FUTURE_TIME_LIMIT            = 60 * 60 * 2;
> 
> const size_t   BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW             = 60;
> 
> // MONEY_SUPPLY - total number coins to be generated
> const uint64_t MONEY_SUPPLY                                  = 1000000000000000;
> const size_t MIN_MIXIN                          = 0;
> const uint8_t MANDATORY_MIXIN_BLOCK_VERSION     = 0;
> const uint32_t MIXIN_START_HEIGHT                          = 0;
> const uint32_t MANDATORY_TRANSACTION                          = 0;
> const uint32_t KILL_HEIGHT                          = 0;
> const uint64_t TAIL_EMISSION_REWARD                          = 0;
> const size_t CRYPTONOTE_COIN_VERSION                          = 0;
> const uint32_t ZAWY_DIFFICULTY_BLOCK_INDEX                 = 0;
> const size_t ZAWY_DIFFICULTY_V2                          = 0;
> const uint8_t ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION   = 3;
> const uint32_t BUGGED_ZAWY_DIFFICULTY_BLOCK_INDEX                 = 0;
> const unsigned EMISSION_SPEED_FACTOR                         = 19;
> const uint64_t GENESIS_BLOCK_REWARD                          = 40000000000000;
> static_assert(EMISSION_SPEED_FACTOR <= 8 * sizeof(uint64_t), "Bad EMISSION_SPEED_FACTOR");
> 
> const size_t   CRYPTONOTE_REWARD_BLOCKS_WINDOW               = 100;
> const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE     = 100000; //size of block (bytes) after which reward for block calculated using block size
> const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V2  = 20000;
> const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V1  = 10000;
> const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_CURRENT = CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE;
> const size_t   CRYPTONOTE_COINBASE_BLOB_RESERVED_SIZE        = 600;
> const size_t   CRYPTONOTE_DISPLAY_DECIMAL_POINT              = 6;
> const uint64_t MINIMUM_FEE                                   = UINT64_C(100000000);    // pow(10, 6)
> const uint64_t DEFAULT_DUST_THRESHOLD                        = UINT64_C(100000000);    // pow(10, 6)
> // Use 0 for default max transaction size limit
> const uint64_t MAX_TRANSACTION_SIZE_LIMIT                          = 100000;
> const uint64_t DEFAULT_FEE                          = MINIMUM_FEE;
> 
> const uint64_t DIFFICULTY_TARGET                             = 120; // seconds
> const uint64_t EXPECTED_NUMBER_OF_BLOCKS_PER_DAY             = 24 * 60 * 60 / DIFFICULTY_TARGET;
> const size_t   DIFFICULTY_WINDOW                             = 17; // blocks
> const size_t   DIFFICULTY_WINDOW_V1                          = 720;
> const size_t   DIFFICULTY_WINDOW_V2                          = 720;
> const size_t   DIFFICULTY_CUT                                = 0;  // timestamps to cut after sorting
> const size_t   DIFFICULTY_CUT_V1                             = 60;
> const size_t   DIFFICULTY_CUT_V2                             = 60;
> const size_t   DIFFICULTY_LAG                                = 0;  // !!!
> const size_t   DIFFICULTY_LAG_V1                             = 15;
> const size_t   DIFFICULTY_LAG_V2                             = 15;
> static_assert(2 * DIFFICULTY_CUT <= DIFFICULTY_WINDOW - 2, "Bad DIFFICULTY_WINDOW or DIFFICULTY_CUT");
> 
> const size_t   MAX_BLOCK_SIZE_INITIAL                        = 100000;
> const uint64_t MAX_BLOCK_SIZE_GROWTH_SPEED_NUMERATOR         = 100 * 1024;
> const uint64_t MAX_BLOCK_SIZE_GROWTH_SPEED_DENOMINATOR       = 365 * 24 * 60 * 60 / DIFFICULTY_TARGET;
> 
> const uint64_t CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS     = 1;
> const uint64_t CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_SECONDS    = DIFFICULTY_TARGET * CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS;
> 
> const uint64_t CRYPTONOTE_MEMPOOL_TX_LIVETIME                = 60 * 60 * 24;     //seconds, one day
> const uint64_t CRYPTONOTE_MEMPOOL_TX_FROM_ALT_BLOCK_LIVETIME = 60 * 60 * 24 * 7; //seconds, one week
> const uint64_t CRYPTONOTE_NUMBER_OF_PERIODS_TO_FORGET_TX_DELETED_FROM_POOL = 7;  // CRYPTONOTE_NUMBER_OF_PERIODS_TO_FORGET_TX_DELETED_FROM_POOL * CRYPTONOTE_MEMPOOL_TX_LIVETIME = time to forget tx
> 
> const size_t   FUSION_TX_MAX_SIZE                            = CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_CURRENT * 30 / 100;
> const size_t   FUSION_TX_MIN_INPUT_COUNT                     = 12;
> const size_t   FUSION_TX_MIN_IN_OUT_COUNT_RATIO              = 4;
> 
> const uint32_t KEY_IMAGE_CHECKING_BLOCK_INDEX                = 0;
> const uint32_t UPGRADE_HEIGHT_V2                                = 1;
> const uint32_t UPGRADE_HEIGHT_V3                                = 985548;
> const unsigned UPGRADE_VOTING_THRESHOLD                      = 90;               // percent
> const uint32_t UPGRADE_VOTING_WINDOW                         = EXPECTED_NUMBER_OF_BLOCKS_PER_DAY;  // blocks
> const uint32_t UPGRADE_WINDOW                                = EXPECTED_NUMBER_OF_BLOCKS_PER_DAY;  // blocks
> static_assert(0 < UPGRADE_VOTING_THRESHOLD && UPGRADE_VOTING_THRESHOLD <= 100, "Bad UPGRADE_VOTING_THRESHOLD");
> static_assert(UPGRADE_VOTING_WINDOW > 1, "Bad UPGRADE_VOTING_WINDOW");
> 
> const char     CRYPTONOTE_BLOCKS_FILENAME[]                  = "blocks.bin";
> const char     CRYPTONOTE_BLOCKINDEXES_FILENAME[]            = "blockindexes.bin";
> const char     CRYPTONOTE_POOLDATA_FILENAME[]                = "poolstate.bin";
> const char     P2P_NET_DATA_FILENAME[]                       = "p2pstate.bin";
> const char     MINER_CONFIG_FILE_NAME[]                      = "miner_conf.json";
> const char     GENESIS_COINBASE_TX_HEX[]                     = "010a01ff00018080aace938c090243d9c15d049ebdee2bab711cfa9eb9372708b0d8f1c2820716c4e640010bd5ef210193f52822f6d6a4605759fd941f09c4438876708dd1b422c2296c2e51e70b0665";
> } // parameters
> 
> const char     CRYPTONOTE_NAME[]                             = "sikka";
> 
> const uint8_t  TRANSACTION_VERSION_1                         =  1;
> const uint8_t  TRANSACTION_VERSION_2                         =  2;
> const uint8_t  CURRENT_TRANSACTION_VERSION                   =  TRANSACTION_VERSION_1;
> const uint8_t  BLOCK_MAJOR_VERSION_1                         =  1;
> const uint8_t  BLOCK_MAJOR_VERSION_2                         =  2;
> const uint8_t  BLOCK_MAJOR_VERSION_3                         =  3;
> const uint8_t  BLOCK_MINOR_VERSION_0                         =  0;
> const uint8_t  BLOCK_MINOR_VERSION_1                         =  1;
> 
> const size_t   BLOCKS_IDS_SYNCHRONIZING_DEFAULT_COUNT        =  10000;  //by default, blocks ids count in synchronizing
> const size_t   BLOCKS_SYNCHRONIZING_DEFAULT_COUNT            =  100;    //by default, blocks count in blocks downloading
> const size_t   COMMAND_RPC_GET_BLOCKS_FAST_MAX_COUNT         =  1000;
> 
> const int      P2P_DEFAULT_PORT                              = 39605;
> const int      RPC_DEFAULT_PORT                              = 39606;
> 
> const size_t   P2P_LOCAL_WHITE_PEERLIST_LIMIT                =  1000;
> const size_t   P2P_LOCAL_GRAY_PEERLIST_LIMIT                 =  5000;
> 
> const size_t   P2P_CONNECTION_MAX_WRITE_BUFFER_SIZE          = 32 * 1024 * 1024; // 32 MB
> const uint32_t P2P_DEFAULT_CONNECTIONS_COUNT                 = 8;
> const size_t   P2P_DEFAULT_WHITELIST_CONNECTIONS_PERCENT     = 70;
> const uint32_t P2P_DEFAULT_HANDSHAKE_INTERVAL                = 60;            // seconds
> const uint32_t P2P_DEFAULT_PACKET_MAX_SIZE                   = 50000000;      // 50000000 bytes maximum packet size
> const uint32_t P2P_DEFAULT_PEERS_IN_HANDSHAKE                = 250;
> const uint32_t P2P_DEFAULT_CONNECTION_TIMEOUT                = 5000;          // 5 seconds
> const uint32_t P2P_DEFAULT_PING_CONNECTION_TIMEOUT           = 2000;          // 2 seconds
> const uint64_t P2P_DEFAULT_INVOKE_TIMEOUT                    = 60 * 2 * 1000; // 2 minutes
> const size_t   P2P_DEFAULT_HANDSHAKE_INVOKE_TIMEOUT          = 5000;          // 5 seconds
> const char     P2P_STAT_TRUSTED_PUB_KEY[]                    = "";
> 
> const char* const SEED_NODES[] = 
> { 
> 	"85.214.128.234:39605",
> 	"45.32.220.216:39605",
> };
> 
> 
> struct CheckpointData {
>   uint32_t index;
>   const char* blockId;
> };
> 
> const std::initializer_list<CheckpointData> CHECKPOINTS = {
> };
> } // CryptoNote
> 
> #define ALLOW_DEBUG_COMMANDS
> 




and the content of conf

> 
> seed-node=85.214.128.234:39605
> seed-node=45.32.220.216:39605
> EMISSION_SPEED_FACTOR=19
> DIFFICULTY_TARGET=120
> CRYPTONOTE_DISPLAY_DECIMAL_POINT=6
> MONEY_SUPPLY=1000000000000000
> GENESIS_BLOCK_REWARD=40000000000000
> SYNC_FROM_ZERO=1
> DEFAULT_DUST_THRESHOLD=100
> MINIMUM_FEE=100
> CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=10
> CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE=100000
> MAX_TRANSACTION_SIZE_LIMIT=100000
> CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=12
> DIFFICULTY_CUT_V1=60
> DIFFICULTY_CUT_V2=60
> DIFFICULTY_CUT=0
> DIFFICULTY_LAG_V1=15
> DIFFICULTY_LAG_V2=15
> DIFFICULTY_LAG=0
> DIFFICULTY_WINDOW_V1=720
> DIFFICULTY_WINDOW_V2=720
> DIFFICULTY_WINDOW=17
> ZAWY_DIFFICULTY_V3=1
> ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION=3
> p2p-bind-port=39605
> rpc-bind-port=39606
> BYTECOIN_NETWORK=48c23319-42a5-7ef9-dd71-6577006aa042
> CRYPTONOTE_NAME=sikka
> GENESIS_COINBASE_TX_HEX=010a01ff00018080aace938c090243d9c15d049ebdee2bab711cfa9eb9372708b0d8f1c2820716c4e640010bd5ef210193f52822f6d6a4605759fd941f09c4438876708dd1b422c2296c2e51e70b0665
> MAX_BLOCK_SIZE_INITIAL=100000
> UPGRADE_HEIGHT_V2=1

**Comment by luiscosio** [comment]
@madradio How did you manage to fix this issue? Having the same issue.

**Comment by zhmrab** [comment]
@madradio Having the exact same problem as well, what's the fix?
