### ISSUE TITLE
GPU miner implementation?

### ISSUE THREAD

**Issue by cycleworm** [forknote/forknote#40]
Hi Guys, 

i started playing around with the forknote resources. i am pretty impressed. 

I wanted to ask if there is also an implementation for an GPU miner? or is it planned?

thx
cycleworm

**Comment by cycleworm** [comment]
Found out that existing mining clients can be used. 
like CPUMiner-Multi, ccminer-cryptonight, Claymore CryptyNote GPU (which supports GPU mining)...

**Comment by xlnd47** [comment]
@cycleworm so how can we do this?
