### ISSUE TITLE
Wallet Sync Issue [Proof of work too weak for block]

### ISSUE THREAD

**Issue by madradio** [forknote/forknote#41]
The sync fails after 55 blocks and gets stuck with warning like this 

> 2017-Oct-29 02:38:37.886433 WARNING [Core] Proof of work too weak for block 970d040c41f3748d6d70ce5bd408f173eac984afce7c3dde298e3be6bd3ba929
> 2017-Oct-29 02:38:46.113903 INFO    [protocol] [153.136.116.252:39605 OUT] Sync data returned unknown top block: 56 -> 26123 [26067 blocks (36 days) behind] 
> 2017-Oct-29 02:38:46.113903 INFO    [protocol] SYNCHRONIZATION started
> 2017-Oct-29 02:38:47.852003 WARNING [Core] Proof of work too weak for block 970d040c41f3748d6d70ce5bd408f173eac984afce7c3dde298e3be6bd3ba929

Any idea where the problem could be? 
I tested it with both Simplewallet and QT wallet from [here](https://github.com/amjuarez/bytecoin-gui) but still it gets stuck at this particular block

**Comment by pmitchev** [comment]
https://bitcointalk.org/index.php?topic=1079306.msg23255440#msg23255440
Contact me with your config file if you created your coin with v2.1.1 and it's a production coin. I will provide you a easy fix

**Comment by madradio** [comment]
When I download the windows binaries from the [site](http://forknote.net/download/) the daemon seems to work fine with the same config. However, when I build the files using cryptonote-generator, it still has the issue of  "wrong block version" error. 

Is it something to do with the JSON file that we create with?

I'll check with the devs for the upgrade and the fix.

**Comment by madradio** [comment]
I moved mysource to V2.1.2 release and now it syncs upto 890 blocks and then I get a different error this time.

> Block 08cb3a09caad4448151636bcacddddafe53ce2dcbbe928c859509cade7beddea has too big cumulative size

I tried changing 

const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE     = 200000; //size of block (bytes) after which reward for block calculated using block size
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V2  = 200000;
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V1  = 200000;

but still throws the same error. I also tried changing MAX_BLOCK_SIZE_GROWTH_SPEED_NUMERATOR & MAX_BLOCK_SIZE_GROWTH_SPEED_DENOMINATOR to a higher value, but this throws up a different error 

> Block reward mismatch for block

Since the binaries of release 2.1.2 seem to sync fine, I'd like to know the JSON file used for building it with cryptonote-generator, so that I can modify the parameters from my config.

**Comment by pmitchev** [comment]
Did you managed to fix it? MAX_BLOCK_SIZE_GROWTH_SPEED_NUMERATOR and MAX_BLOCK_SIZE_GROWTH_SPEED_DENOMINATOR are never changed. 
Do you produce the json with "f_get_blockchain_settings" or by hand?

**Comment by madradio** [comment]
I did create json manually by copying the content of the config. Now with 2.1.2 release and forknote.json, it's so far syncing is fine and crossed the point where it had issues..

**Comment by indigencoin** [comment]
Hi @pmitchev I'm trying to migrate on a new server and I'm getting this same error. But I've been using version 2.1.2 ever since. I'm just trying to run on a new server. What's the fix on the config file?

**Comment by indigencoin** [comment]
The only solution I could figure out was to download the entire blockchain and no let it sync from height 0

**Comment by helder-garcia** [comment]
@pmitchev I'm having the "Proof of work too weak for block" problem. I saw your message to another user requesting him to send a message to you in private. I couldn't find how to do it in github, so I'm posting here. Could you help me fixing the problem?

**Comment by jonsparks** [comment]
I'm having the same issue. I was able to get past it earlier by resetting my blockchain on all but one node, but it happened again about 600 blocks later.

**Comment by pmitchev** [comment]
Can you share your config if the seed nodes are still up? 
I am trying to debug this but I cannot replicate it

**Comment by jonsparks** [comment]
Sure, both seeds are still up (currently around block 1060 since I had reset everything).

```
seed-node=69.30.205.90:34122
seed-node=13.68.21.165:34122
EMISSION_SPEED_FACTOR=19
DIFFICULTY_TARGET=120
CRYPTONOTE_DISPLAY_DECIMAL_POINT=12
MONEY_SUPPLY=18446744073709551615
GENESIS_BLOCK_REWARD=368934881474191040
SYNC_FROM_ZERO=1
DEFAULT_DUST_THRESHOLD=1000000
MINIMUM_FEE=1000000
CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=10
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE=100000
MAX_TRANSACTION_SIZE_LIMIT=100000
CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=406
DIFFICULTY_CUT_V1=60
DIFFICULTY_CUT_V2=60
DIFFICULTY_CUT=0
DIFFICULTY_LAG_V1=15
DIFFICULTY_LAG_V2=15
DIFFICULTY_LAG=0
DIFFICULTY_WINDOW_V1=720
DIFFICULTY_WINDOW_V2=720
DIFFICULTY_WINDOW=17
p2p-bind-port=34122
rpc-bind-port=34123
BYTECOIN_NETWORK=8196e6e2-7369-4de6-7937-501ae4003ed9
CRYPTONOTE_NAME=SPARK
GENESIS_COINBASE_TX_HEX=010a01ff0001c0bd94dc9e8aae8f05028f7a0c355abeced9976d82e5d06ab581f9b31f8c3b90d9ae505b5c3edb84b7ad21012a925361643af113c3e22a1be754890029d8c3966e6d57f2a9f61b4fa5320d6b
MAX_BLOCK_SIZE_INITIAL=100000
UPGRADE_HEIGHT_V2=1
UPGRADE_HEIGHT_V3=30
```

**Comment by pmitchev** [comment]
Тhank you. Please keep up the seed nodes up until it's debugged

**Comment by jonsparks** [comment]
Will do, the seeds are on dedicated servers so they shouldn't be going anywhere.

**Comment by pmitchev** [comment]
@jonsparks I am getting this when I try to sync. Is the config correct?
WARNING Failed to validate block 1202ecaaa43625ac89a28d321d509d0403a679d8f029652404138fe3c229a342: Wrong block version

**Comment by zhmrab** [comment]
@pmitchev @jonsparks 

Hey guys, I seem to have a similar issue with the cryptonote-generator on ubuntu, it doesn't do that with Forknote 

Block 3 -> 5 WARNING Failed to validate block : Wrong block version

Any idea what to do to fix it?

**Comment by pmitchev** [comment]
@zhmrab You probably don't have bug-fixes.json in your extensions

**Comment by zhmrab** [comment]
I didn't at first so I added it but the problem still persists... the only other solution I see is to download the entire blockchain instead of sync from 0

**Comment by jonsparks** [comment]
@pmitchev I regenerated my config and reset the blockchain, it's working so far with 4 machines in the network- let me know if you want me to update my config in my previous comment.

**Comment by cryptoluka** [comment]
I'm having this issue..

2018-Jan-17 17:05:19.417415 WARNING [Core] Proof of work too weak for block 1121b12b9240e3e7b3d77ec3f5f51a3309c53dadea859980ffa6ffcd4496f7d0
2018-Jan-17 17:05:29.276615 INFO    [protocol] [131.221.32.78:52420 OUT] Sync data returned unknown top block: 144 -> 223 [79 blocks (0 days) behind] 

I deleted ZAWY config of config file but are the same problem

**Comment by spotme-main** [comment]
I am having a similar issue.  I believe this is a platform issue.  Right now I get the "Proof of work too weak for block" error on the Windows client but not on ubuntu client.  Im running windows 10 pro and 2.12 forknote

**Comment by zhmrab** [comment]
For me I got it on ubuntu 14 as well..

**Comment by pmitchev** [comment]
@zhmrab do you still have the nodes up? Share the config if you have the nodes up

**Comment by zhmrab** [comment]
@pmitchev thank you, unfortuantely I dont I trashed the servers, moved on to work on a Monero based coin instead!

**Comment by indigencoin** [comment]
I face the same issue on new Windows clients, but there's a quick fix for that, simply download the bootstrapped blockchain and put it on the nodes db folder then run forknote daemon. This happens if you mined the genesis block on a Windows client and you have already mined several blocks before running forknote on a new client.

**Comment by zhmrab** [comment]
@indigencoin 

Yeah but not ideal if every new user of the coin has to do that as well in order to be able to sync.. 
I ended up editing Core.cpp I will let you know if this fix works

**Comment by indigencoin** [comment]
Good to know @zhmrab I have no problem with it because I did not release a desktop wallet due to the technicalities involve to operate it. I only made web wallets using walletd since it doesn't have issues that I face with the desktop wallet. Please do let us know if you made a fix. Thanks.

**Comment by zhmrab** [comment]
@indigencoin in src/Core.cpp commented like this

   } // else if (!currency.checkProofOfWork(cryptoContext, cachedBlock, currentDifficulty)) {
    // logger(Logging::WARNING) << "Proof of work too weak for block " << cachedBlock.getBlockHash();
    // return error::BlockValidationError::PROOF_OF_WORK_TOO_WEAK;
  //}

hope this helps

**Comment by indigencoin** [comment]
BTW @zhmrab are you using Windows 10? Have you successfully built it on Windows? For some reasons, I'm having issues with the latest MinGW.

**Comment by zhmrab** [comment]
@indigencoin haven't dealt with Windows yet but compiled on mac 10.13 and ubuntu 16, i will deal with  Windows once I sort the pool mining issues...

**Comment by luiscosio** [comment]
@indigencoin Come join us at https://t.me/forknote so we can help you out with the Windows compilation

**Comment by zhmrab** [comment]
@pmitchev @indigencoin 

So it seems commenting Core.cpp doesn't do the trick anymore, the generated binaries aren't validating blocks for the same reason it seems, 

@pmitchev do you know of any fix to fix those blocks not getting validated ? 
Thanks!

Here's my conf : 

seed-node=xx.xx.xx.xx:xxxx
seed-node=xx.xx.xx.xx:xxxx
EMISSION_SPEED_FACTOR=18
DIFFICULTY_TARGET=120
CRYPTONOTE_DISPLAY_DECIMAL_POINT=4
MONEY_SUPPLY=1000000000000
GENESIS_BLOCK_REWARD=100000000000
SYNC_FROM_ZERO=1
DEFAULT_DUST_THRESHOLD=0
MINIMUM_FEE=0
CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=10
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE=100000
MAX_TRANSACTION_SIZE_LIMIT=100000
CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=120
DIFFICULTY_CUT_V1=60
DIFFICULTY_CUT_V2=60
DIFFICULTY_CUT=0
DIFFICULTY_LAG_V1=15
DIFFICULTY_LAG_V2=15
DIFFICULTY_LAG=0
DIFFICULTY_WINDOW_V1=720
DIFFICULTY_WINDOW_V2=720
DIFFICULTY_WINDOW=17
p2p-bind-port=4596
rpc-bind-port=4597
BYTECOIN_NETWORK=454b008a-e9ef-286a-5df0-83b57cc201d9
CRYPTONOTE_NAME=testcoin
GENESIS_COINBASE_TX_HEX=010a01ff000180dce4b2970202968cf1a258b73649448b2497d515123c1276f4c9f83538fa43769e427aa8acee210119bf981c21b857437d10049377beec49b5142588a38bcac73765b1c85a7ae700
MAX_BLOCK_SIZE_INITIAL=100000
UPGRADE_HEIGHT_V2=1
UPGRADE_HEIGHT_V3=300000000

**Comment by SWTCoin** [comment]
@pmitchev , Except me all others are having this issue. "Sync data returned unknown top block: 1->5 [4 blocks <o days> behind] Warning failed to validate block 3dfb4.... : Transaction has wrong unlock time"  and due to this they are not able to see their balance. daemon does not get updated.. Any solution? But when they send me their .wallet file to me check I can open it and see the balance!
![4 1](https://user-images.githubusercontent.com/38393672/41498620-d84ec3c0-718f-11e8-9dce-e2298249adfd.png)

**Comment by inzider** [comment]
Have any one found a way around the "proof of work too weak" here? I tested previous version I don't recall that error. LWMA or ZAWY implementation issue maybe and setting a high block height here could help (ZAWY_DIFFICULTY_BLOCK_INDEX=0)?
