### ISSUE TITLE
transaction size too big? MAX_TRANSACTION_SIZE_LIMIT needed?

### ISSUE THREAD

**Issue by cycleworm** [forknote/forknote#43]
hi, 

why is the transaction size needed in the config of forknote?
**MAX_TRANSACTION_SIZE_LIMIT=xx**

Can is be safely removed?

When i make a huge transaction with simplewallet i get the error
"**transaction size too big**" could this error be eliminated by deleting 
this config entry or making it bigger?

What would be the disadvantage by doing that?

**Comment by pmitchev** [comment]
The default value is 125000. In most cases removing MAX_TRANSACTION_SIZE_LIMIT will cause stuck transactions

**Comment by cycleworm** [comment]
ok thx for the Info. ans how big could it be set?
what is the unit of this key? (bytes? oder Nummer of Transactions?) 

what are recommendations for getting rid of the transaction size too big Error?

**Comment by pmitchev** [comment]
The unit is bytes. Value is calculated by multiplying CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE * 1.25 
Possible solutions - 1. reduce mixing; 2 . consolidate outputs in your wallet or; 3. resend and hope better random outputs are chosen.

**Comment by cycleworm** [comment]
i even got the error "transaction size too big" when transfering huge amounts of coins with mixin "0". 
with consolidating you mean for example trying to split the transaction in the wallet?

what can be 

CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V1 and
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V2 used for?

thanks

**Comment by theinsignificantbit** [comment]
SO, can we increase;
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE
to raise the transaction size?

**Comment by pmitchev** [comment]
Yes, but you must do it when you generate the coin

**Comment by vitorgamer58** [comment]
Can we change this parameter after the currency is already generated if all users run the new code? We create a coin of 336 million coins and as it is still very little has some big transactions being demanded, in the order of 50K, if changing the parameter and everyone updating the Daemon of all right?
