### ISSUE TITLE
Block verification failed, dropping connection: Proof of work is too weak

### ISSUE THREAD

**Issue by cycleworm** [forknote/forknote#44]
Hi Guys, 

on a new client i try to sync to my blockchain. after starting to sync i get an warning from the beginning that sys. 

**WARNING Proof of work too weak for block 11c3d0542d56cf9fea84d80109e147eaa23c8f7c4e6c6933c18eeae12c3f6450**

It syncs a few blocks till it gets stuck at block 31.

![image](https://user-images.githubusercontent.com/493769/32690848-a4ba03e0-c6fd-11e7-9818-c23f0cd68e04.png)

i already deleted the whole DB files in Roaming Folder in Windows.  And tried so sync again. 
That did not solve it.
Any ideas what causes this problem? and how to solve it ?

thanks.

**Comment by cycleworm** [comment]
one flag in the coin config file was changed. DIFFICULTY_LAG from 0 to 10
Thats why it did not work. 
Changed it back. works again.

**Comment by pmitchev** [comment]
Using zawy difficulty alg with lag is probably not the best idea. Best option you have is to remove all parameters containing ZAWY in it until there is a fix

**Comment by cycleworm** [comment]
hi @pmitchev thx for the info. i just have them in my config because they were generated on the forknote.net/create site.

![image](https://user-images.githubusercontent.com/493769/32694208-ab58c1e0-c73a-11e7-8c3a-b6962b1d19ff.png)

i am not really sure what the zawy fags are doing. (and there are a lot more where i do not know if it is good to use them or not.

![image](https://user-images.githubusercontent.com/493769/32694214-d99d582c-c73a-11e7-84e3-6eaab1559370.png)


is there somewhere a document which tags a recommended if a coin is created with the latest forknote?

thanks

**Comment by pmitchev** [comment]
Zawy difficulty algorith will minimize a nicehash attack on your coin. You can introduce it later in your coin after a certain block height with ZAWY_DIFFICULTY_BLOCK_INDEX

**Comment by cycleworm** [comment]
thanks. 

Why are these tags then generated in the config maker, if they should not be used?

#**is there somewhere a document which tags a recommended if a coin is created with the latest forknote?**
