### ISSUE TITLE
walletd Failed to read wallet version

### ISSUE THREAD

**Issue by sakshamapp** [forknote/forknote#45]
This error is generated after the command :  ./walletd --config configs/krscoin.conf --local

2017-Nov-14 07:30:10.591233 ERROR   Failed to read wallet version
2017-Nov-14 07:30:10.591964 ERROR   Failed to init walletService reason: Failed to read wallet version: Wrong version

**Comment by pmitchev** [comment]
simplewallet and walletd use different file format.
Also, you should first generate with -g flag

**Comment by sakshamapp** [comment]
Thank You
