### ISSUE TITLE
Seed Node Exception

### ISSUE THREAD

**Issue by qraz** [forknote/forknote#47]
I have compiled the project and was able to run the daemon successfully.

I added 2 seed nodes to the config and copied the binaries and config files to those machines.
Now that I tried to start the seed node, I get a warning like this

> WARNING [169.203.179.130:32822 INC] Exception in connectionHandler: TcpConnection::read
> WARNING [169.203.179.130:39193 INC] Exception in connectionHandler: TcpConnection::read

169.203.179.130 is the IP of the seed itself, Do I need to have the own seed IP in the config file when I run the seed node? If I remove the own IP from the config file where I run seed node, the warning doesn't show.  I am not sure if this is even right way to do it.

I also tried with --p2p-external-port=<portnum>

I made sure the port is open and I am able to connect to it using telnet from a windows machine.

**Comment by cycleworm** [comment]
i think you need to have at least 2 seed nodes in your config file. have you started both daemons with the same config file? Maybe your defined ports are blocked?

**Comment by qraz** [comment]
The issue happened when the binaries were built from the 2.1.2 code. Later when I downloaded the binaries directly from the forknote site, this disappeared. I'll check again to confirm it.

**Comment by trideout** [comment]
I'm getting the same issue here, Exception in connectionHandler: TcpConnection::read on my seeds
All necessary ports are open, but it seems to be trying to connect to arbitrary ports. I'm also having trouble getting a local daemon to sync up to the seeds.

**Comment by prashantprabhakar** [comment]
@qraz What binaries are you using? If  you could provide a link .

**Comment by qraz** [comment]
@prashantprabhakar I downloaded the binaries from [here](http://forknote.net/download/)

**Comment by francescosganga** [comment]
same here, how to solve it?
