### ISSUE TITLE
“SYNCHRONIZED OK” messages is not showing for new config coin.

### ISSUE THREAD

**Issue by ArtRaptors** [forknote/forknote#50]
I generated new coin using [config](http://forknote.net/create/#/) and [generator](https://github.com/forknote/cryptonote-generator/) but “SYNCHRONIZED OK” is not appearing on my laptop, on VPS and seed nodes as well.

It is showing like this messages:

> asus@TAL1:~/forknote-linux$ ls
> configs  forknoted  miner  simplewallet  walletd
> asus@TAL1:~/forknote-linux$ ./forknoted --config-file configs/TAL.conf
> Success: Configuration file openned: "configs/TAL.conf"
> 2017-Dec-03 19:39:02.419865 INFO    forknote v2.1.2.1251 ()
> 2017-Dec-03 19:39:02.420007 INFO    Module folder: ./forknoted
> 2017-Dec-03 19:39:02.420199 INFO    Opening DB in /home/asus/.tal/DB
> 2017-Dec-03 19:39:02.458699 INFO    DB opened in /home/asus/.tal/DB
> 2017-Dec-03 19:39:02.458896 INFO    Initializing core...
> 2017-Dec-03 19:39:02.460247 INFO    Core initialized OK
> 2017-Dec-03 19:39:02.460404 INFO    Initializing p2p server...
> 2017-Dec-03 19:39:02.460513 INFO    Binding on 0.0.0.0:25853
> 2017-Dec-03 19:39:02.460607 INFO    Net service binded on 0.0.0.0:25853
> 2017-Dec-03 19:39:02.460799 INFO    Attempting to add IGD port mapping.
> 2017-Dec-03 19:39:06.465430 INFO    No IGD was found.
> 2017-Dec-03 19:39:06.465531 INFO    P2p server initialized OK
> 2017-Dec-03 19:39:06.466122 INFO    Starting core rpc server on address 127.0.0.1:25854
> 2017-Dec-03 19:39:06.466189 INFO    Core rpc server started ok
> 2017-Dec-03 19:39:06.466224 INFO    Starting p2p net loop...
> 2017-Dec-03 19:39:06.466248 INFO    Starting node_server
> 2017-Dec-03 19:39:06.466728 INFO    
> 2017-Dec-03 19:39:06.466728 INFO    **********************************************************************
> 2017-Dec-03 19:39:06.466728 INFO    You are now synchronized with the network. You may now start simplewallet.
> 2017-Dec-03 19:39:06.466728 INFO    
> 2017-Dec-03 19:39:06.466728 INFO    Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
> 2017-Dec-03 19:39:06.466728 INFO    Otherwise, you will possibly need to synchronize the blockchain again.
> 2017-Dec-03 19:39:06.466728 INFO    
> 2017-Dec-03 19:39:06.466728 INFO    Use "help" command to see the list of available commands.
> 2017-Dec-03 19:39:06.466728 INFO    **********************************************************************
> exit
> 2017-Dec-03 19:44:45.712090 INFO    Stop signal sent
> 2017-Dec-03 19:44:45.712214 INFO    Stopping NodeServer and it's2 connections...
> 2017-Dec-03 19:44:45.712437 INFO    NodeServer loop stopped
> 2017-Dec-03 19:44:45.712471 INFO    p2p net loop stopped
> 2017-Dec-03 19:44:45.712496 INFO    Stopping core rpc server...
> 2017-Dec-03 19:44:45.712536 INFO    Deinitializing p2p...
> SwappedVector cache hits: 0, misses: 1 (100.00%)
> SwappedVector cache hits: 0, misses: 1 (100.00%)
> 2017-Dec-03 19:44:45.712874 INFO    Closing DB.
> 2017-Dec-03 19:44:45.771471 INFO    Node stopped.
> 

Looks like it is working but something is missing. 
Do I have to create wallet and mine something first or what should me my first steps?

_I need help to get clone coin up and running ASAP. 
Let me know if someone have experience and can help me to finalize everything fast._

**Comment by indigencoin** [comment]
It looks like your daemon is ok from the looks of it, its connected with your seed nodes.
Just create a wallet with simplewallet, then run the miner to start mining coins.
