### ISSUE TITLE
RPC Wallet as a Windows Service Not Working

### ISSUE THREAD

**Issue by indigencoin** [forknote/forknote#51]
Hi, has anyone tried using walletd as a service in Windows?

**Comment by indigencoin** [comment]
It seems the service wont start. I checked the list of running Services and the Payment Gate won't start. Whenever I manually start the service, it just stops again. Has anybody experienced the same?

**Comment by indigencoin** [comment]
OK never mind i finally made it work.

**Comment by pmitchev** [comment]
Share the solution mate :) Probably someone else will be stuck at the same spot and your comment will help him

**Comment by indigencoin** [comment]
Sure mate! Here's what I did, firstly the Bytecoin wiki are very outdated, last update 2015. For example, their samples still use single quotes, that's not a valid JSON format, they must be double quotes.

Now when you execute RPC Wallet as a service, do not use the simpewallet's config file. 

simplewallet wallet requires you to put your config inside configs/ folder: eg. configs/mycoin.conf
walletd ignores a custom --config parameter. 

I checked the source code and it always reads the files "payment_service.conf" located at same directory as the walletd. So I copied configs/mycoin.conf to payment_services.conf (same folder as walletd) and added the following configurations (of course don't forget to generate first container file where to keep all wallet addresses, using the --generate-container command):

container-file=anyfilename
container-password=anypassword
daemon-address=127.0.0.1
daemon-port=8080 <-- this port must point to your forknote daemon
bind-address=127.0.0.1
bind-port=8070
testnet=no

1. First run forknote daemon
2. Run walletd --config payment_service.conf --register-service --daemon

At this point walletd is not running if you look at the Services console

3. Run walletd again with the following parameter only:

walletd --config payment_service.conf 

The wallet will execute but will not show a command prompt. It is only listening at this url for your json formatted posts:

http://127.0.0.1:8070/json_rpc

Lastly, do not forget to add all your bound ports in your Windows Advanced Firewall settings and allow both Incoming and Outgoing.

**Comment by indigencoin** [comment]
I reopened this issue so others can still view it for some tips.

**Comment by Z3roacces** [comment]
İndigencoin can i ask can you write me 2xx template. Miner  options like./miner - - address xxxxx port or anything,  i cant make mining this fork my university graduation thesis if i cant Profs says Good Luck next year please help me!?

**Comment by indigencoin** [comment]
Z3roaccess I can only understand the "good luck next year" part. But the miner stuff please explain.
