### ISSUE TITLE
./miner not working on Linux 

### ISSUE THREAD

**Issue by Z3roacces** [forknote/forknote#52]
Hello im forking bytecoin on this document but i see after monero Major bug 2.xx miners not work, How to mine New fork or others . /miner - - address xxxxx - - threads 7 not working help me please?

**Comment by pmitchev** [comment]
it works. You need to specify the daemon port too.

**Comment by Z3roacces** [comment]
Hm i cant making beacause there is no Stable version of forknote Just 1.xx Stable i see now my deamon staying starting node_Server there is no results about seed nodes simplewallet have error 3 How can i fix thats all?  Probably you say seed node Server Got problem but i tryed all of versions x2 time not working ?

**Comment by Z3roacces** [comment]
And i see 1.0.11 working Good deamon have no problem to connected2.me seed Server and mining, simplewallet others work!  but 2xx all of them staying starting node_Server why ?

**Comment by zhmrab** [comment]
I'm having this issue too, how to you specify the daemon port in order to mine?

**Comment by jared201** [comment]
i'm getting CoreIsBusy on this one

**Comment by zhmrab** [comment]
I just put ./miner --address X --daemon-rpc-port Y and it worked for me
