### ISSUE TITLE
Mining errors 2x 

### ISSUE THREAD

**Issue by Z3roacces** [forknote/forknote#53]
Can someone explain me next week i had graduation thesis and i need the show professors to mine windrawal etc. İ have problem to mining im running the deamon synching ok mining not working 2x How can i do this can someone write me   . /miner - - address xxxxxxxxxxxxxxxxx like command ?

**Comment by pmitchev** [comment]
The correct use is:
./miner --address X --daemon-rpc-port Y

Use ./miner --help for more info
