### ISSUE TITLE
CHECKPOINT FAILED FOR HEIGHT 79000

### ISSUE THREAD

**Issue by nclinh** [forknote/forknote#61]
Dear, 

My coin build on Forknote get this error

2017-Dec-28 07:08:23.144989 INFO    [daemon] forknote v1.0.10.687 ()
2017-Dec-28 07:17:35.643693 INFO    [miner] Found block for difficulty: 12455
2017-Dec-28 07:17:35.646397 ERROR   [checkpoints] CHECKPOINT FAILED FOR HEIGHT 79000. EXPECTED HASH: cae33204e624faeb64938d80073bb7bbacc27017dc63f36c5c0f313cad455a02, FETCHED HASH: 37fcb8bf4966b5ab2a388d37583fe886fbeeb93cf314d0f68fc721b9fa59bd66
2017-Dec-28 07:17:35.646602 ERROR   [Blockchain] CHECKPOINT VALIDATION FAILED
2017-Dec-28 07:17:35.924734 ERROR   [core] mined block failed verification

Walletd RPC stop at 

{"id":"test","jsonrpc":"2.0","result":{"blockCount":78999,"knownBlockCount":79000,"lastBlockHash":"0af30f0d576fd4ae468bbd3dba7401719a009fc094ab093ee8b35522a1e6db91","peerCount":4}}

Please help me. I add checkpoint 

CHECKPOINT=79000:cae33204e624faeb64938d80073bb7bbacc27017dc63f36c5c0f313cad455a02

but it is not working.

**Comment by pmitchev** [comment]
did you restarted the daemon? Try to add checkpoint before 79000

**Comment by nclinh** [comment]
Thank you for rely me,
I restarted and cleared cache (.mycoin folder), checkpoint before 79000 , What is format it ? 
Thank you very much pmitchev

**Comment by pmitchev** [comment]
CHECKPOINT=31000:fd1bd97b1ab45f8d0238e423f7c2c1a6f5afc7da141782baf72690d127c02edd

The same format you use. Are you using "bytecoin" as a coin name? The default checkpoints should only activated when "bytecoin" is used for a name

**Comment by nclinh** [comment]
Thank pmitchev, 
But i don't use "bytecoin" as a name coin, i have been set "extestcoin" as a coin name. I try add checkpoint in another config file (etc: bytecoin,conf, dashcoin.conf...) , 
and I updated new version for forknoted (https://github.com/forknote/forknote/releases/tag/2.1.2) but it is not working.

**Comment by pmitchev** [comment]
Can you show me what checkpoint are you trying to add to Dashcoin for example? I can tell you what you are doing wrong this way.

**Comment by nclinh** [comment]
This is my config file extestcoin.conf

EMISSION_SPEED_FACTOR=18
DIFFICULTY_TARGET=120
CRYPTONOTE_DISPLAY_DECIMAL_POINT=2
MONEY_SUPPLY=20000000000
GENESIS_BLOCK_REWARD=0
DEFAULT_DUST_THRESHOLD=0
MINIMUM_FEE=1
CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=10
CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE=100000
MAX_TRANSACTION_SIZE_LIMIT=100000
CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=1
DIFFICULTY_CUT_V1=60
DIFFICULTY_CUT_V2=60
DIFFICULTY_CUT=0
DIFFICULTY_LAG_V1=15
DIFFICULTY_LAG_V2=15
DIFFICULTY_LAG=0
DIFFICULTY_WINDOW_V1=720
DIFFICULTY_WINDOW_V2=720
DIFFICULTY_WINDOW=17
ZAWY_DIFFICULTY_V3=1
ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION=3
p2p-bind-port=33377
rpc-bind-port=11177
BYTECOIN_NETWORK=51d3e089-d6de-1865-1502-076fc300ba79
CRYPTONOTE_NAME=extestcoin
GENESIS_COINBASE_TX_HEX=
MAX_BLOCK_SIZE_INITIAL=100000
UPGRADE_HEIGHT_V2=1
UPGRADE_HEIGHT_V3=30

CHECKPOINT=28000:70d2531151529ac00bf875281e15f51324934bc85e5733dcd92e1ccb1a665ff8
CHECKPOINT=40000:c181ec9223a91fef8658c7aa364c093c41c28d250870ca1ed829bf74f0abf038
CHECKPOINT=55000:5289fe9f2dce8f51441019b9fbc85c70ad85ff49a666ef0109f3269890c6af6d
CHECKPOINT=70000:193e335f34b8b8f1fab3857111cb668c2720340e80176a25155071e573481acb
CHECKPOINT=87500:cce8a035f34457ec1098ab41e5949cac3db00ebff3503e26f36bfa057543095a
CHECKPOINT=150000:118989862ef4903df981501aae6f5178aee794bdbceb8e01fe76ee15ab960d52
CHECKPOINT=200000:bb5b339991347c3b06431b233d3dbf9201e9176ddf4349ee46c60473725d5c98
CHECKPOINT=250000:c5b6064258237e911300cdcb6f937b37a6c17932e2bfdcba0ff12a48694709e0
CHECKPOINT=298000:5b1f21234c911eb755abce6fa66358558b380526f606222d042eb8b7ce993ae8
CHECKPOINT=360000:d9426fcdaa95a8dd2f1d151c2088a0dac2143963b8088d0de02f9c08ec8429f5
CHECKPOINT=423000:7e2c45f1a546290a7f7f28cb83c1bdc21f531f410ad0e65a12a5c86b95e194b5
CHECKPOINT=78999:cae33204e624faeb64938d80073bb7bbacc27017dc63f36c5c0f313cad455a02
CHECKPOINT=76300:1c8edae49d33ea3e09fed7d0ffcceb0b4255dc5bd32026ff33967c5fb77ccf6a
CHECKPOINT=142000:9fb3d1278935be048c52b9dba981a6015973032603ab2f2d0c59ef83d5b73064

seed-node=<MY_VPS_IP>:33377
seed-node=<MY_VPS_IP>:33378

Thank pmitchev

**Comment by jpmadeira** [comment]
Hi, how do I add checkpoint to my code?

**Comment by pmitchev** [comment]
Just add this to your config file. With your hashes and heights ofc:

`CHECKPOINT=28000:70d2531151529ac00bf875281e15f51324934bc85e5733dcd92e1ccb1a665ff8
`
