### ISSUE TITLE
forkenoted --config-file ignores config file when launching

### ISSUE THREAD

**Issue by hrmmmwhynot** [forknote/forknote#64]
So, I downloaded the linux cli tar from forknote.net and generating the wallet and the genesis block seemed fine with my configs/customcoin.conf.

Then I ran the daemon .. using --config-file configs/customcoin.conf with log-level 5 and I see that the daemon is connecting to bytecoin peer and seed nodes on port 8080 (seed.bytecoin.org) ? 

I specified my seed-nodes in the conf file and I also tried using --add-exclusive-node option and it seemed to just go ahead and ignore that and connect straight to bytecoin network.

`2017-Dec-29 01:03:33.453827 INFO    Initializing p2p server...
2017-Dec-29 01:03:33.505129 TRACE   Added seed node: 45.76.29.96:8080 (seed.bytecoin.org)
2017-Dec-29 01:03:33.505979 TRACE   Added seed node: 85.25.201.95:8080 (85.25.201.95)
2017-Dec-29 01:03:33.506360 TRACE   Added seed node: 85.25.196.145:8080 (85.25.196.145)
2017-Dec-29 01:03:33.506719 TRACE   Added seed node: 85.25.196.146:8080 (85.25.196.146)
2017-Dec-29 01:03:33.506997 TRACE   Added seed node: 85.25.196.144:8080 (85.25.196.144)
2017-Dec-29 01:03:33.507336 TRACE   Added seed node: 5.199.168.138:8080 (5.199.168.138)
2017-Dec-29 01:03:33.507976 TRACE   Added seed node: 62.75.236.152:8080 (62.75.236.152)
2017-Dec-29 01:03:33.508523 TRACE   Added seed node: 85.25.194.245:8080 (85.25.194.245)
2017-Dec-29 01:03:33.508886 TRACE   Added seed node: 95.211.224.160:8080 (95.211.224.160)
2017-Dec-29 01:03:33.509222 TRACE   Added seed node: 144.76.200.44:8080 (144.76.200.44)
`

**Comment by blueavenue** [comment]
Do you have solved the issue?

If not, post your conf-file here.

**Comment by pmitchev** [comment]
If you are using systemd or upstart, you need full path for the config file
