### ISSUE TITLE
Need help with mining!

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#65]
Hey everyone,

So I'm a using forknote on 2 ubuntu vps, the daemon seems to be working fine and the simplewallet as well but my bc_height is still =0 !

Whenever I open the miner ./miner --address nothing happens so I want to know if I'm doing this wrong or what can I do in order to start mining!

So far everything has been working smoothly but I may be missing something! Please let me know!

**Comment by indigencoin** [comment]
It takes a while to mine the first block. It could take several hours. Just leave the miner and simplewallet running overnight.

**Comment by jared201** [comment]
any progress on this one I'm also trying to mine

**Comment by zhmrab** [comment]
So far nothing but I will let it sit and let you all know :)

**Comment by zhmrab** [comment]
Hey guys, 

So I left the miner run for about a day now but bc_height is still 0...
Any idea on how to fix that ?

**Comment by zhmrab** [comment]
Need to specify --daemon-rpc-port Y, closing this
