### ISSUE TITLE
./miner is blank 

### ISSUE THREAD

**Issue by sakshamapp** [forknote/forknote#67]
./miner   --daemon-host 0.0.0.0 --daemon-rpc-port 36151  --address [ADDRESS]
this command is not giving any response ,mining is not working

**Comment by pmitchev** [comment]
the miner program does not have any outputs

**Comment by VluCash** [comment]
Try ./miner --address  "Your Wallet Address"

I hope this helps

**Comment by lakshaygaur** [comment]
set --log-level 5 and you'll start seeing details on terminal.
