### ISSUE TITLE
Premine Coins

### ISSUE THREAD

**Issue by NEO2756** [forknote/forknote#69]
steps followed:
1. Built new coin and simple wallet (with premine coins --> 40% of total supply)
2. Generated GENESIS_COINBASE_TX_HEX with wallet address (which will hold premine coins)
3. Added GENESIS_COINBASE_TX_HEX to config.json file.
4. Build the coin again.
5. where are the premined coins? wallet address used at step "2" still showing zero balance.

**Comment by zhmrab** [comment]
You need to start mining first

**Comment by NEO2756** [comment]
I forgot to mentioned that I have started the mining using following command , my bad...
$ ./miner --address <step 2 address>
Doubts: 
1. Few transactions are getting mined, by bc_height is 10 but premine coins transactiin is not there.
2. Frim where other transactions are comming to the miner? Miner is local in my machine.

**Comment by zhmrab** [comment]
Ok so,

1. the premine should be in the wallet with the address that you specify when you generated, 
GENESIS_COINBASE_TX_HEX with wallet address, try to type reset in the wallet so it will resync from 0 which is where your premined coins are.

2. This is the concept of mining, by solving blocks for the network you are awarded coins, each block containing and defined amount of coins, it's not so much of a transaction but more of a reward for helping the network itself to make it simple

**Comment by NEO2756** [comment]
Thanks for quick respnose :)
1. yes, i did it. what I observed is: sometimes it sync from 0 block and coins appears but when I did a rebuild after some changes in config (seed IP change) with a fresh --data-dir, it again not showing the premined coins. its random on linux as per https://github.com/forknote/forknote/issues/17   but this is a closed issue :(.
2. ok...thats cool.

**Comment by zhmrab** [comment]
When you edit your conf do you print a new genesis tx ?

**Comment by NEO2756** [comment]
Yes I followed all the steps metioned in first post. You can say i created coin again from scratch....just coz I need to change the config.

**Comment by VluCash** [comment]
If you basically rebuilt the coin from scratch will need to create a new wallet address to hold the pre mined coins.
