### ISSUE TITLE
RPC sendTrasnaction destination empty ?

### ISSUE THREAD

**Issue by lanaiscool** [forknote/forknote#73]
Im getting destination empty when trying to send a transaction what does this code mean im almost done with my web wallet but im hanging on this point

**Comment by zhmrab** [comment]
Are you using the generator?

**Comment by lanaiscool** [comment]
yes i am using the generator

**Comment by lanaiscool** [comment]
bump

**Comment by lanaiscool** [comment]
can be closed fixed
