### ISSUE TITLE
im staying at node_server whats mean ?

### ISSUE THREAD

**Issue by mountandlaser** [forknote/forknote#75]
hello there im starter of cryptonote but i cant open to 2.1.2 version of deamon deamon is staying starting node server i was wait 5 hours there is nothing happen, then after im try to 1.0.1 version deamon is working mining and wallet is not work synching error i have node catgory 3 can someone help me ? 
sorry for my eng best regards,

**Comment by VluCash** [comment]
Are you running 2 Seed Nodes simultaneously?

**Comment by mountandlaser** [comment]
yes i am running 2 nodes different computers or vps servers on linux/windows but not working any way i cant see peer list other computers something wrong ?

**Comment by VluCash** [comment]
Run your 2 Seed nodes then run the Daemon on your local machine.  Paste here your output:errors

**Comment by mountandlaser** [comment]
ok i will try 2-3 days i have alot of job to do , and i will send pictures
