### ISSUE TITLE
GUI for forknote 

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#76]
So been working on a GUI for Forknote and it is working fine so far but currently struggling to bundle the app so I could have other people using it...

I am not a developer so if anyone has any idea how to do this please write me or comment here!

**Comment by pmitchev** [comment]
I will post this on bitcointalk. I hope someone will be able to help you.

**Comment by zhmrab** [comment]
@pmitchev thank you, I found a solution using :

windeployqt
macdeployqt
linuxdeployqt

**Comment by fengshuicoin** [comment]
Plan on releaseing gui wallet source?

**Comment by zhmrab** [comment]
@fengshuicoin Yes, still working on it. Currently running into issues with the wallet's integrated miner but hopefully will same a repo to share soon

**Comment by fengshuicoin** [comment]
Mind sharing early maybe i can help.
I been trying to fork chavezcoinwallet and testing inside out.

**Comment by techqc** [comment]
Why are you using this if you don't know to use this.
When you don't know what you are doing please don't create another shity coin
