### ISSUE TITLE
BCN sync

### ISSUE THREAD

**Issue by noglance** [forknote/forknote#77]
it's not syncing with BCN (about week at 1438187)

endstring(182) "{"id":"burmar42","jsonrpc":"2.0","result":{"blockCount":1438187,"knownBlockCount":1,"lastBlockHash":"d7ab399c9f5e87a1b4b7d643a3810e501e25afcb5a3b3ea0ed280606b101b547","peerCount":0}}"

**Comment by pmitchev** [comment]
Do you still have this issue?

**Comment by noglance** [comment]
@pmitchev for old apps from bytecoin and forknode — yes. I'm just downloading new sources and could tell how it's working only after it would be compiled
