### ISSUE TITLE
Issues with premine

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#80]
Having issues with premine at this time.. 

writing mycoin.conf / creating simpewallet / 
then 
./forknoted --config-file configs/mandela.conf --print-genesis-tx --genesis-block-reward-address xxxxxxx

Replacing with new genesis hex in mycoin.conf and when starting the seed nodes getting this
[BlockchainSynchronizer] Failed to load: genesis block hash does not match stored state, read XXXXXX
INFO    available balance: 0.0000, locked amount: 0.0000

Any ideas? Must be missing something...

**Comment by michaellu88** [comment]
i am not sure is my solution correct? i delete the /.fakecoin/db folder

**Comment by zhmrab** [comment]
Closing this,
