### ISSUE TITLE
Issue when running 2 seeds, local daemon + wallet

### ISSUE THREAD

**Issue by The99** [forknote/forknote#84]
Hey all,

I'm running two seed daemons on Ubuntu Amazon Lightsail. P2P port 29999 RDP 30000.

The two seeds seem to see each other and communicate.

As soon as I run the forknoted on local machine, the two seeds freak out, block mismatch error and keep repeating blocks 1-5. I also can't tell if I received the premined tokens. Here's an image of the error:

![image](https://user-images.githubusercontent.com/36016474/35774237-12f426ee-0937-11e8-97ef-8e5e6d5d1241.png)

Can someone set me on the right direction?

**Comment by blueavenue** [comment]
I see no error! Do you have tried following:
./minerd --daemon-host localhost:30000 --address yourwalletaddresshere

Is port 30000 free? Try

netstat -l and show listen ports

Or delete your blockchain DB and restart both Daemon on VPS, than start Daemon on local machine. 
DB can be found in root/.yourcoin

You can hidden folder show with CTRL + H (i think its correct, can test it from here)

Do you have upstart the service in etc/init?

**Comment by pmitchev** [comment]
Hi,
Github issues must be used only for reporting software bugs.
