### ISSUE TITLE
Simple wallet Error

### ISSUE THREAD

**Issue by PandaDudz** [forknote/forknote#91]
Hi again. I have a problem with simple wallet. Daemon seems to be running . Here is screenshot.
![1518638733013696812198](https://user-images.githubusercontent.com/6645217/36225423-e735ea82-11ca-11e8-911e-6a6902fa73f0.jpg)

**Comment by spotme-main** [comment]
That's a weird one..  havent seen that one before.

**Comment by PandaDudz** [comment]
Of course i do... im gonna try this when i get home :D 
![screenshot_20180215-130800](https://user-images.githubusercontent.com/6645217/36256024-77a84dd6-1251-11e8-89ef-72c1250c1c8c.jpg) 
This looks like the same error @spotme-main
