### ISSUE TITLE
MIX_IN

### ISSUE THREAD

**Issue by vitorgamer58** [forknote/forknote#95]
so I know MIX IN is how many signatures besides your the transaction needs and has direct connection with the level of anonymity in the transaction, so far so good but ... is there a limit to the MIX_IN? Has anyone made a transaction using 701 as MIX_IN, can this delay the network? can be considered a type of attack against the currency? thank you :)
![MIX_IN](http://ap.imagensbrasil.org/images/2018/02/24/Screenshot_420.png)

**Comment by intrinsiccoin** [comment]
I think, the transaction can get rejected if there are not that many transactions in a block. I don't think it as an attack on the network. Only one that can lose out in the transaction is the sender with the transfer not getting executed.
