### ISSUE TITLE
Is forknote going to uptade to Bytecoin 3.0? 

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#96]
Just wondering :)

**Comment by pmitchev** [comment]
Yes, when it's out of beta and it's tested for problems

**Comment by zhmrab** [comment]
Ok! Looking forward to it!

**Comment by zhmrab** [comment]
@pmitchev Just wondering will it be possible for a forknote 2.1 based coin to update to Bytecoin 3.0? 

I've been messing with the new bytecoin repo but been running into a lot of issues regarding seed nodes and handshakes

**Comment by Doestoievski** [comment]
@pmitchev it's out of beta. any plans for bytecoin 3.0?
