### ISSUE TITLE
walletd sendTransaction / simplewallet transfer rpc call dont work

### ISSUE THREAD

**Issue by saloppe73** [forknote/forknote#98]
Hi! Get an error (Bad address) after the sendTransaction rpc call to walletd or the transfer rpc call to simplewallet:

`[error] => stdClass Object
        (
            [code] => -32000
            [data] => stdClass Object
                (
                    [application_code] => 7
                )
            [message] => Bad address
        )
    [id] => sendTransaction
    [jsonrpc] => 2.0`

`[error] => stdClass Object
        (
            [code] => -4
            [message] => Bad address
        )
    [id] => transfer
    [jsonrpc] => 2.0`

Any hints?
Thanks && Regards!

**Comment by saloppe73** [comment]
have fix it

**Comment by ZiXXiV** [comment]
Well, How?! Care to let the community know how you've fixed it? You're the people that make Google worse, finding someone else with the same problem but ending up with no results..

Awesome!

**Comment by MyGaCoDev** [comment]
Ok... Some help with me please...
This is the JSON used with command "sendTransaction", where:
GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i is the address wallet with balance in the container
and GXCFrxvo1FKCS15Ei2WicN5iyK1BmZ3PZMHrFEFzqy8Gd4itTq7t1tP1iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHJX5fkJ is the destination.... but
``{  
  "params":{  
     "anonymity":6,
     "fee":0.01000000,
     "unlockTime":0,
     "paymentId":"",
     "addresses":[  
        "GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i"
     ],
     "transfers":[  
        {  
           "amount":123.00000000,
"address":"GXCFrxvo1FKCS15Ei2WicN5iyK1BmZ3PZMHrFEFzqy8Gd4itTq7t1tP1iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHJX5fkJ"
        }
     ],
"changeAddress":"GW5oHPeQmtbcGB1d4suNd1ChNdw2hubQfUpqGVh9XzWnAUDwFUvTLM91iKgYmCfbzqb7eDZje79kh44oiRHt7QfkHLYeX6i"
  },
  "jsonrpc":"2.0",
  "id":"23",
  "method":"sendTransaction"
}``

I got the following error:
{"error":{"code":-32600,"message":"Invalid Request"},"id":"23","jsonrpc":"2.0"}

Any idea?

**Comment by flodaq** [comment]
The fees and amount must be whole numbers. Multiply then by the precision length of the coin.
